### ISSUE TITLE
Adding limiting number of messages feature

### ISSUE THREAD

**Issue by patrizok** [3bl3gamer/tg-history-dumper#5]
Feature Request: Adding limiting number of messages feature:

For example for limiting feature works like; channels dump 5k messages, for user type dump all.

In addition to this dumping contact list is useful here. Active sessions list also good.

**Comment by 3bl3gamer** [comment]
Thank you for feature ideas.

> Active sessions list also good.

What do you mean? Just listing (in terminal) current active sessions (same as in settings → privacy → active sessions)? Or dumping/logging then in some way?

**Comment by patrizok** [comment]
Hi thank for response,

1-
I mean dumping and saving **active sessions** (same as in settings → privacy → active sessions) to a file.

2-
Dump **contacts**  (menu → contacts) to file feature
(mtproto has this function)
https://github.com/3bl3gamer/tgclient/blob/9d36603bcc1b953757d8c620596938fe72418b81/mtproto/mtproto.go#L712

3- 
Adding limiting number of messages feature is also important for big groups and channels. It can be set in config.json.

If you want to contact with me you can write Telegram: @patrizok, I can test the new features.
Thanks

**Comment by 3bl3gamer** [comment]
There are optional limits now: https://github.com/3bl3gamer/tg-history-dumper#history-limits
