### ISSUE TITLE
Socks Proxy Authentication Support

### ISSUE THREAD

**Issue by patrizok** [3bl3gamer/tg-history-dumper#8]
Hello

Socks5 proxies generally needs username and password authentication, so proxy option can not be useful most of the case.

Can you please add authentication support for proxies.

https://github.com/3bl3gamer/tg-history-dumper/blob/df78833158cdea8e20d2603f5e5411aeb2afabce/tg.go#L84

3. parameter is SOCKS5 proxy Auth parameter actually. Just need to get parameters from config/parameters.

Thanks

**Comment by 3bl3gamer** [comment]
Done, thanks for the suggestion.
